const mrtStations = new Set([
    "jurong east", "bukit batok", "bukit gombak", "brickland", "choa chu kang", "yew tee", "sungei kadut", "kranji", "marsiling", "woodlands", "admiralty", "sembawang", "canberra", "yishun", "khatib", "yio chu kang", "ang mo kio", "bishan", "braddell", "toa payoh", "novena", "newton", "orchard", "somerset", "dhoby ghaut", "city hall", "raffles place", "marina bay", "marina south pier",
    "pasir ris", "tampines", "simei", "tanah merah", "bedok", "kembangan", "eunos", "paya lebar", "aljunied", "kallang", "lavender", "bugis", "city hall", "raffles place", "tanjong pagar", "outram park", "tiong bahru", "redhill", "queenstown", "commonwealth", "buona vista", "dover", "clementi", "jurong east", "chinese garden", "lakeside", "boon lay", "pioneer", "joo koon", "gul circle", "tuas crescent", "tuas west road", "tuas link", "expo", "changi airport",
    "harbourfront", "outram park", "chinatown", "clarke quay", "dhoby ghaut", "little india", "farrer park", "boon keng", "potong pasir", "woodleigh", "serangoon", "kovan", "hougang", "buangkok", "sengkang", "punggol", "punggol coast",
    "dhoby ghaut", "bras basah", "esplanade", "promenade", "nicoll highway", "stadium", "mountbatten", "dakota", "paya lebar", "macpherson", "tai seng", "bartley", "serangoon", "lorong chuan", "bishan", "marymount", "caldecott", "bukit brown", "botanic gardens", "farrer road", "holland village", "buona vista", "one north", "kent ridge", "haw par villa", "pasir panjang", "labrador park", "telok blangah", "harbourfront", "bayfront", "marina bay",
    "bukit panjang", "cashew", "hillview", "hume", "beauty world", "king albert park", "sixth avenue", "tan kah kee", "botanic gardens", "stevens", "newton", "little india", "rochor", "bugis", "promenade", "bayfront", "downtown", "telok ayer", "chinatown", "fort canning", "bencoolen", "jalan besar", "bendemeer", "geylang bahru", "mattar", "macpherson", "ubi", "kaki bukit", "bedok north", "bedok reservoir", "tampines west", "tampines", "tampines east", "upper changi", "expo",
    "woodlands north", "woodlands", "woodlands south", "springleaf", "lentor", "mayflower", "bright hill", "upper thomson", "caldecott", "mount pleasant", "stevens", "napier", "orchard boulevard", "orchard", "great world", "havelock", "outram park", "maxwell", "shenton way", "marina bay", "marina south", "gardens by the bay", "founders' memorial", "tanjong rhu", "katong park", "tanjong katong", "marine parade", "marine terrace", "siglap", "bayshore"
]);

const mallNames = new Set([
    "100 am", "313@somerset", "aperia", "balestier hill shopping centre", "bugis cube", "bugis junction", "bugis+", "capitol piazza", "cathay cineleisure orchard", "clarke quay central", "the centrepoint", "city square mall", "city gate mall", "citylink mall", "duo", "far east plaza", "funan", "great world city", "grid", "hdb hub", "holland village shopping mall", "ion orchard", "junction 8", "knightsbridge", "liat towers", "lucky plaza", "marina bay sands", "the shoppes at marina bay sands", "marina bay link mall", "marina square", "millenia walk", "mustafa shopping centre", "ngee ann city", "one holland village", "orchard central", "orchard gateway", "orchard plaza", "midpoint orchard", "palais renaissance", "people's park centre", "people's park complex", "plaza singapura", "raffles city", "scotts square", "shaw house and centre", "sim lim square", "singapore shopping centre", "the south beach", "square 2", "sunshine plaza", "suntec city", "tanglin mall", "tanjong pagar centre", "tekka centre", "the adelphi", "the paragon", "tiong bahru plaza", "the poiz", "thomson plaza", "united square", "thomson v", "velocity@novena square", "wheelock place", "wisma atria", "zhongshan mall",
    "bedok mall", "century square", "city plaza", "changi city point", "downtown east", "djitsun mall bedok", "eastpoint mall", "jewel changi airport", "kinex", "katong shopping centre", "katong square", "kallang wave mall", "leisure park kallang", "i12 katong", "our tampines hub", "parkway parade", "pasir ris mall", "pasir ris west plaza", "paya lebar square", "paya lebar quarter", "roxy square", "singpost centre", "tampines 1", "tampines mall", "white sands", "elias mall", "loyang point",
    "888 plaza", "admiralty place", "amk hub", "canberra plaza", "causeway point", "hdb hub", "broadway plaza", "jubilee square", "junction 8", "junction nine", "marsiling mall", "northpoint city", "sembawang shopping centre", "sun plaza", "vista point", "wisteria mall", "woodlands civic centre", "woodlands mart", "woodlands north plaza",
    "anchorvale village", "buangkok square", "compass one", "greenwich v", "heartland mall", "hougang 1", "hougang green shopping mall", "hougang mall", "nex", "northshore plaza", "oasis terraces", "punggol coast mall", "punggol plaza", "rivervale mall", "rivervale plaza", "sengkang grand mall", "the seletar mall", "upper serangoon shopping centre", "waterway point", "myvillage at serangoon garden",
    "beauty world centre", "beauty world plaza", "bukit panjang plaza", "bukit timah plaza", "fajar shopping centre", "greenridge shopping centre", "hillion mall", "hillv2", "junction 10", "keat hong shopping centre", "limbang shopping centre", "lot one", "rail mall", "sunshine place", "teck whye shopping centre", "west mall", "yew tee point", "yew tee square",
    "vivocity", "harbourfront centre", "alexandra retail centre",
    "321 clementi", "the clementi mall", "imm", "jem", "westgate", "jurong point", "pioneer mall", "the star vista", "alexandra central", "anchorpoint", "od mall", "boon lay shopping centre", "grantral mall", "fairprice hub", "gek poh shopping centre", "rochester mall", "taman jurong shopping centre", "west coast plaza", "plantation plaza", "tengah mall", "queensway shopping centre", "the rail mall"
]);
